site_name: 快猫安卓版下载_快猫短视频app官方下载2025最新版_华军软件园
site_author: 快猫短视频
site_description: 快猫安卓版是一款优质实用的短视频交流社区。快猫短视频app软件力至于提供优质好看的资源，花费大量精力和时间去追寻，只为用户的优质体验，这是开发这款软件的理念，从用户的角度出发，用户永远是排在第一位。APP界面简洁大方、优美，所有模块一目了然。
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
